version: '3.8'
services:
  web:
    image: php:7.4-apache
    container_name: contenedor_php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
    networks:
      - my_network

  db:
    image: mysql:5.7
    container_name: contenedor_mysql
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /ysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data: